directories:
  output: release
  buildResources: build
appId: com.uvcc.camera-lister
productName: Camera Lister
files:
  - filter:
      - app/**/*
      - dist/**/*
      - node_modules/**/*
      - package.json
mac:
  category: public.app-category.utilities
  icon: app/assets/icon.icns
win:
  target: nsis
  icon: app/assets/icon.ico
linux:
  target: AppImage
  icon: app/assets/icon.png
electronVersion: 38.2.1
